project:
  type: book
  output-dir: docs

book:
  title: "Adaptation Notes"
  author: "James Holland Jones"
  date: "10/07/2025"
  chapters:
    - index.qmd
    - models.qmd
    - evolution.qmd
    - populations.qmd
    - culture.qmd
    - decision.qmd
    - complex.qmd
    - commons.qmd
    - dynamic.qmd
    - efficiency.qmd
    - robust.qmd
    - references.qmd

bibliography: adaptation.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



